backend:
  name: github
  repo: ifaisalabid1/techie-faisal
  branch: main
  base_url: https://techiefaisal.pages.dev/
  auth_endpoint: /api/auth
  squash_merges: true
publish_mode: editorial_workflow
media_folder: 'src/content/img'
public_folder: '../img'
collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/content/articles'
    create: true
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'URL', name: 'url', widget: 'string' }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Publish Date'
        name: 'pubDate'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - label: 'Related Articles'
        name: 'relatedArticles'
        widget: 'list'
        required: false
      - { label: 'Body', name: 'body', widget: 'markdown' }
